package dev.dot.files.mimetype

import kotlinx.collections.immutable.ImmutableList
import kotlinx.collections.immutable.persistentListOf
import kotlinx.collections.immutable.toImmutableList

data class MimeType(val type: String, val subtype: String, val extensions: ImmutableList<String>) {
    constructor(
        type: String,
        subtype: String,
        vararg extensions: String,
    ) : this(
        type,
        subtype,
        persistentListOf(*extensions),
    )

    fun matches(extension: String): Boolean {
        return extensions.any { it.equals(extension, ignoreCase = true) }
    }

    override fun toString(): String {
        return "$type/$subtype"
    }
}

// Automatically parsed from:
// https://github.com/patrickmccallum/mimetype-io/raw/master/src/mimeData.json
object MimeTypes {
    fun getMimeType(extension: String): MimeType? {
        extension.removePrefix(".")
        return Map.firstOrNull { it.matches(extension) }
    }

    fun getMimeType(type: String, subtype: String): MimeType? {
        return Map.firstOrNull {
            it.type.equals(type, ignoreCase = true) && it.subtype.equals(subtype, ignoreCase = true)
        }
    }

    fun getExtensions(type: String): ImmutableList<String> {
        return Map.filter { it.type.equals(type, ignoreCase = true) }
            .flatMap { it.extensions }
            .toImmutableList()
    }

    fun getExtensions(type: String, subtype: String): ImmutableList<String> {
        return Map.firstOrNull {
                it.type.equals(type, ignoreCase = true) &&
                    it.subtype.equals(subtype, ignoreCase = true)
            }
            ?.extensions ?: persistentListOf()
    }

    private val Map =
        persistentListOf(
            MimeType("application", "andrew-inset", "ez"),
            MimeType("application", "applixware", "aw"),
            MimeType("application", "atom+xml", "atom"),
            MimeType("application", "atomcat+xml", "atomcat"),
            MimeType("application", "atomsvc+xml", "atomsvc"),
            MimeType("application", "ccxml+xml", "ccxml"),
            MimeType("application", "cu-seeme", "cu"),
            MimeType("application", "davmount+xml", "davmount"),
            MimeType("application", "ecmascript", "ecma"),
            MimeType("application", "emma+xml", "emma"),
            MimeType("application", "epub+zip", "epub"),
            MimeType("application", "font-tdpfr", "pfr"),
            MimeType("application", "gzip", "gz", ".tgz"),
            MimeType("application", "hyperstudio", "stk"),
            MimeType("application", "java-archive", "jar"),
            MimeType("application", "java-serialized-object", "ser"),
            MimeType("application", "java-vm", "class"),
            MimeType("application", "json", "json"),
            MimeType("application", "lost+xml", "lostxml"),
            MimeType("application", "mac-binhex40", "hqx"),
            MimeType("application", "mac-compactpro", "cpt"),
            MimeType("application", "marc", "mrc"),
            MimeType("application", "mathematica", "ma", ".mb", "nb"),
            MimeType("application", "mathml+xml", "mathml", "mml"),
            MimeType("application", "mbox", "mbox"),
            MimeType("application", "mediaservercontrol+xml", "mscml"),
            MimeType("application", "mp4", "mp4s"),
            MimeType("application", "msword", "doc", "dot", "wiz"),
            MimeType("application", "mxf", "mxf"),
            MimeType(
                "application",
                "octet-stream",
                "a",
                ".bin",
                "bpk",
                "deploy",
                "dist",
                "distz",
                "dmg",
                "dms",
                "dump",
                "elc",
                "lha",
                "lrf",
                "lzh",
                "o",
                ".obj",
                "pkg",
                "so",
            ),
            MimeType("application", "oda", "oda"),
            MimeType("application", "oebps-package+xml", "opf"),
            MimeType("application", "ogg", "ogx"),
            MimeType("application", "onenote", "onepkg", "onetmp", "onetoc", "onetoc2"),
            MimeType("application", "patch-ops-error+xml", "xer"),
            MimeType("application", "pdf", "pdf"),
            MimeType("application", "pgp-encrypted", "pgp"),
            MimeType("application", "pgp-signature", "asc", "sig"),
            MimeType("application", "pics-rules", "prf"),
            MimeType("application", "pkcs10", "p10"),
            MimeType("application", "pkcs7-mime", "p7c", "p7m"),
            MimeType("application", "pkcs7-signature", "p7s"),
            MimeType("application", "pkix-cert", "cer"),
            MimeType("application", "pkix-crl", "crl"),
            MimeType("application", "pkix-pkipath", "pkipath"),
            MimeType("application", "pkixcmp", "pki"),
            MimeType("application", "pls+xml", "pls"),
            MimeType("application", "postscript", "ai", ".eps", "ps"),
            MimeType("application", "prql", "prql"),
            MimeType("application", "prs.cww", "cww"),
            MimeType("application", "rdf+xml", "rdf"),
            MimeType("application", "reginfo+xml", "rif"),
            MimeType("application", "relax-ng-compact-syntax", "rnc"),
            MimeType("application", "resource-lists+xml", "rl"),
            MimeType("application", "resource-lists-diff+xml", "rld"),
            MimeType("application", "rls-services+xml", "rs"),
            MimeType("application", "rsd+xml", "rsd"),
            MimeType("application", "rss+xml", "rss", "xml"),
            MimeType("application", "rtf", "rtf"),
            MimeType("application", "sbml+xml", "sbml"),
            MimeType("application", "scvp-cv-request", "scq"),
            MimeType("application", "scvp-cv-response", "scs"),
            MimeType("application", "scvp-vp-request", "spq"),
            MimeType("application", "scvp-vp-response", "spp"),
            MimeType("application", "sdp", "sdp"),
            MimeType("application", "set-payment-initiation", "setpay"),
            MimeType("application", "set-registration-initiation", "setreg"),
            MimeType("application", "shf+xml", "shf"),
            MimeType("application", "smil+xml", "smi", "smil"),
            MimeType("application", "sparql-query", "rq"),
            MimeType("application", "sparql-results+xml", "srx"),
            MimeType("application", "srgs", "gram"),
            MimeType("application", "srgs+xml", "grxml"),
            MimeType("application", "ssml+xml", "ssml"),
            MimeType("application", "vnd.3gpp.pic-bw-large", "plb"),
            MimeType("application", "vnd.3gpp.pic-bw-small", "psb"),
            MimeType("application", "vnd.3gpp.pic-bw-var", "pvb"),
            MimeType("application", "vnd.3gpp2.tcap", "tcap"),
            MimeType("application", "vnd.3m.post-it-notes", "pwn"),
            MimeType("application", "vnd.accpac.simply.aso", "aso"),
            MimeType("application", "vnd.accpac.simply.imp", "imp"),
            MimeType("application", "vnd.acucobol", "acu"),
            MimeType("application", "vnd.acucorp", "acutc", "atc"),
            MimeType("application", "vnd.adobe.air-application-installer-package+zip", "air"),
            MimeType("application", "vnd.adobe.xdp+xml", "xdp"),
            MimeType("application", "vnd.adobe.xfdf", "xfdf"),
            MimeType("application", "vnd.airzip.filesecure.azf", "azf"),
            MimeType("application", "vnd.airzip.filesecure.azs", "azs"),
            MimeType("application", "vnd.amazon.ebook", "azw"),
            MimeType("application", "vnd.americandynamics.acc", "acc"),
            MimeType("application", "vnd.amiga.ami", "ami"),
            MimeType("application", "vnd.android.package-archive", "apk"),
            MimeType("application", "vnd.anser-web-certificate-issue-initiation", "cii"),
            MimeType("application", "vnd.anser-web-funds-transfer-initiation", "fti"),
            MimeType("application", "vnd.antix.game-component", "atx"),
            MimeType("application", "vnd.apple.installer+xml", "mpkg"),
            MimeType("application", "vnd.arastra.swi", "swi"),
            MimeType("application", "vnd.audiograph", "aep"),
            MimeType("application", "vnd.blueice.multipass", "mpm"),
            MimeType("application", "vnd.bmi", "bmi"),
            MimeType("application", "vnd.businessobjects", "rep"),
            MimeType("application", "vnd.chemdraw+xml", "cdxml"),
            MimeType("application", "vnd.chipnuts.karaoke-mmd", "mmd"),
            MimeType("application", "vnd.cinderella", "cdy"),
            MimeType("application", "vnd.claymore", "cla"),
            MimeType("application", "vnd.clonk.c4group", "c4d", "c4f", "c4g", "c4p", "c4u"),
            MimeType("application", "vnd.commonspace", "csp"),
            MimeType("application", "vnd.contact.cmsg", "cdbcmsg"),
            MimeType("application", "vnd.cosmocaller", "cmc"),
            MimeType("application", "vnd.crick.clicker", "clkx"),
            MimeType("application", "vnd.crick.clicker.keyboard", "clkk"),
            MimeType("application", "vnd.crick.clicker.palette", "clkp"),
            MimeType("application", "vnd.crick.clicker.template", "clkt"),
            MimeType("application", "vnd.crick.clicker.wordbank", "clkw"),
            MimeType("application", "vnd.criticaltools.wbs+xml", "wbs"),
            MimeType("application", "vnd.ctc-posml", "pml"),
            MimeType("application", "vnd.cups-ppd", "ppd"),
            MimeType("application", "vnd.curl.car", "car"),
            MimeType("application", "vnd.curl.pcurl", "pcurl"),
            MimeType("application", "vnd.data-vision.rdz", "rdz"),
            MimeType("application", "vnd.debian.binary-package", "deb", "udeb"),
            MimeType("application", "vnd.denovo.fcselayout-link", "fe_launch"),
            MimeType("application", "vnd.dna", "dna"),
            MimeType("application", "vnd.dolby.mlp", "mlp"),
            MimeType("application", "vnd.dpgraph", "dpg"),
            MimeType("application", "vnd.dreamfactory", "dfac"),
            MimeType("application", "vnd.dynageo", "geo"),
            MimeType("application", "vnd.ecowin.chart", "mag"),
            MimeType("application", "vnd.enliven", "nml"),
            MimeType("application", "vnd.epson.esf", "esf"),
            MimeType("application", "vnd.epson.msf", "msf"),
            MimeType("application", "vnd.epson.quickanime", "qam"),
            MimeType("application", "vnd.epson.salt", "slt"),
            MimeType("application", "vnd.epson.ssf", "ssf"),
            MimeType("application", "vnd.eszigno3+xml", "es3", "et3"),
            MimeType("application", "vnd.ezpix-album", "ez2"),
            MimeType("application", "vnd.ezpix-package", "ez3"),
            MimeType("application", "vnd.fdf", "fdf"),
            MimeType("application", "vnd.fdsn.mseed", "mseed"),
            MimeType("application", "vnd.fdsn.seed", "dataless", "seed"),
            MimeType("application", "vnd.flographit", "gph"),
            MimeType("application", "vnd.fluxtime.clip", "ftc"),
            MimeType("application", "vnd.framemaker", "book", "fm", ".frame", "maker"),
            MimeType("application", "vnd.frogans.fnc", "fnc"),
            MimeType("application", "vnd.frogans.ltf", "ltf"),
            MimeType("application", "vnd.fsc.weblaunch", "fsc"),
            MimeType("application", "vnd.fujitsu.oasys", "oas"),
            MimeType("application", "vnd.fujitsu.oasys2", "oa2"),
            MimeType("application", "vnd.fujitsu.oasys3", "oa3"),
            MimeType("application", "vnd.fujitsu.oasysgp", "fg5"),
            MimeType("application", "vnd.fujitsu.oasysprs", "bh2"),
            MimeType("application", "vnd.fujixerox.ddd", "ddd"),
            MimeType("application", "vnd.fujixerox.docuworks", "xdw"),
            MimeType("application", "vnd.fujixerox.docuworks.binder", "xbd"),
            MimeType("application", "vnd.fuzzysheet", "fzs"),
            MimeType("application", "vnd.genomatix.tuxedo", "txd"),
            MimeType("application", "vnd.geogebra.file", "ggb"),
            MimeType("application", "vnd.geogebra.tool", "ggt"),
            MimeType("application", "vnd.geometry-explorer", "gex", "gre"),
            MimeType("application", "vnd.gerber", "gbr"),
            MimeType("application", "vnd.gmx", "gmx"),
            MimeType("application", "vnd.google-earth.kml+xml", "kml"),
            MimeType("application", "vnd.google-earth.kmz", "kmz"),
            MimeType("application", "vnd.grafeq", "gqf", "gqs"),
            MimeType("application", "vnd.groove-account", "gac"),
            MimeType("application", "vnd.groove-help", "ghf"),
            MimeType("application", "vnd.groove-identity-message", "gim"),
            MimeType("application", "vnd.groove-injector", "grv"),
            MimeType("application", "vnd.groove-tool-message", "gtm"),
            MimeType("application", "vnd.groove-tool-template", "tpl"),
            MimeType("application", "vnd.groove-vcard", "vcg"),
            MimeType("application", "vnd.handheld-entertainment+xml", "zmm"),
            MimeType("application", "vnd.hbci", "hbci"),
            MimeType("application", "vnd.hhe.lesson-player", "les"),
            MimeType("application", "vnd.hp-hpgl", "hpgl"),
            MimeType("application", "vnd.hp-hpid", "hpid"),
            MimeType("application", "vnd.hp-hps", "hps"),
            MimeType("application", "vnd.hp-jlyt", "jlt"),
            MimeType("application", "vnd.hp-pcl", "pcl"),
            MimeType("application", "vnd.hp-pclxl", "pclxl"),
            MimeType("application", "vnd.hydrostatix.sof-data", "sfd-hdstx"),
            MimeType("application", "vnd.hzn-3d-crossword", "x3d"),
            MimeType("application", "vnd.ibm.minipay", "mpy"),
            MimeType("application", "vnd.ibm.modcap", "afp", "list3820", "listafp"),
            MimeType("application", "vnd.ibm.rights-management", "irm"),
            MimeType("application", "vnd.ibm.secure-container", "sc"),
            MimeType("application", "vnd.iccprofile", "icc", "icm"),
            MimeType("application", "vnd.igloader", "igl"),
            MimeType("application", "vnd.immervision-ivp", "ivp"),
            MimeType("application", "vnd.immervision-ivu", "ivu"),
            MimeType("application", "vnd.intercon.formnet", "xpw", "xpx"),
            MimeType("application", "vnd.intu.qbo", "qbo"),
            MimeType("application", "vnd.intu.qfx", "qfx"),
            MimeType("application", "vnd.ipunplugged.rcprofile", "rcprofile"),
            MimeType("application", "vnd.irepository.package+xml", "irp"),
            MimeType("application", "vnd.is-xpr", "xpr"),
            MimeType("application", "vnd.jam", "jam"),
            MimeType("application", "vnd.jcp.javame.midlet-rms", "rms"),
            MimeType("application", "vnd.jisp", "jisp"),
            MimeType("application", "vnd.joost.joda-archive", "joda"),
            MimeType("application", "vnd.kahootz", "ktr", "ktz"),
            MimeType("application", "vnd.kde.karbon", "karbon"),
            MimeType("application", "vnd.kde.kchart", "chrt"),
            MimeType("application", "vnd.kde.kformula", "kfo"),
            MimeType("application", "vnd.kde.kivio", "flw"),
            MimeType("application", "vnd.kde.kontour", "kon"),
            MimeType("application", "vnd.kde.kpresenter", "kpr", "kpt"),
            MimeType("application", "vnd.kde.kspread", "ksp"),
            MimeType("application", "vnd.kde.kword", "kwd", "kwt"),
            MimeType("application", "vnd.kenameaapp", "htke"),
            MimeType("application", "vnd.kidspiration", "kia"),
            MimeType("application", "vnd.kinar", "kne", "knp"),
            MimeType("application", "vnd.koan", "skd", "skm", "skp", "skt"),
            MimeType("application", "vnd.kodak-descriptor", "sse"),
            MimeType("application", "vnd.llamagraphics.life-balance.desktop", "lbd"),
            MimeType("application", "vnd.llamagraphics.life-balance.exchange+xml", "lbe"),
            MimeType("application", "vnd.lotus-1-2-3", "123"),
            MimeType("application", "vnd.lotus-approach", "apr"),
            MimeType("application", "vnd.lotus-freelance", "pre"),
            MimeType("application", "vnd.lotus-notes", "nsf"),
            MimeType("application", "vnd.lotus-organizer", "org"),
            MimeType("application", "vnd.lotus-screencam", "scm"),
            MimeType("application", "vnd.lotus-wordpro", "lwp"),
            MimeType("application", "vnd.macports.portpkg", "portpkg"),
            MimeType("application", "vnd.mcd", "mcd"),
            MimeType("application", "vnd.medcalcdata", "mc1"),
            MimeType("application", "vnd.mediastation.cdkey", "cdkey"),
            MimeType("application", "vnd.mfer", "mwf"),
            MimeType("application", "vnd.mfmp", "mfm"),
            MimeType("application", "vnd.micrografx.flo", "flo"),
            MimeType("application", "vnd.micrografx.igx", "igx"),
            MimeType("application", "vnd.mif", "mif"),
            MimeType("application", "vnd.mobius.daf", "daf"),
            MimeType("application", "vnd.mobius.dis", "dis"),
            MimeType("application", "vnd.mobius.mbk", "mbk"),
            MimeType("application", "vnd.mobius.mqy", "mqy"),
            MimeType("application", "vnd.mobius.msl", "msl"),
            MimeType("application", "vnd.mobius.plc", "plc"),
            MimeType("application", "vnd.mobius.txf", "txf"),
            MimeType("application", "vnd.mophun.application", "mpn"),
            MimeType("application", "vnd.mophun.certificate", "mpc"),
            MimeType("application", "vnd.mozilla.xul+xml", "xul"),
            MimeType("application", "vnd.ms-artgalry", "cil"),
            MimeType("application", "vnd.ms-cab-compressed", "cab"),
            MimeType(
                "application",
                "vnd.ms-excel",
                "xla",
                "xlb",
                "xlc",
                "xlm",
                "xls",
                "xlt",
                "xlw",
            ),
            MimeType("application", "vnd.ms-excel.addin.macroenabled.12", "xlam"),
            MimeType("application", "vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb"),
            MimeType("application", "vnd.ms-excel.sheet.macroenabled.12", "xlsm"),
            MimeType("application", "vnd.ms-excel.template.macroenabled.12", "xltm"),
            MimeType("application", "vnd.ms-fontobject", "eot"),
            MimeType("application", "vnd.ms-htmlhelp", "chm"),
            MimeType("application", "vnd.ms-ims", "ims"),
            MimeType("application", "vnd.ms-lrm", "lrm"),
            MimeType("application", "vnd.ms-pki.seccat", "cat"),
            MimeType("application", "vnd.ms-pki.stl", "stl"),
            MimeType("application", "vnd.ms-powerpoint", "pot", "ppa", "pps", "ppt", "pwz"),
            MimeType("application", "vnd.ms-powerpoint.addin.macroenabled.12", "ppam"),
            MimeType("application", "vnd.ms-powerpoint.presentation.macroenabled.12", "pptm"),
            MimeType("application", "vnd.ms-powerpoint.slide.macroenabled.12", "sldm"),
            MimeType("application", "vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm"),
            MimeType("application", "vnd.ms-powerpoint.template.macroenabled.12", "potm"),
            MimeType("application", "vnd.ms-project", "mpp", "mpt"),
            MimeType("application", "vnd.ms-word.document.macroenabled.12", "docm"),
            MimeType("application", "vnd.ms-word.template.macroenabled.12", "dotm"),
            MimeType("application", "vnd.ms-works", "wcm", "wdb", "wks", "wps"),
            MimeType("application", "vnd.ms-wpl", "wpl"),
            MimeType("application", "vnd.ms-xpsdocument", "xps"),
            MimeType("application", "vnd.mseq", "mseq"),
            MimeType("application", "vnd.musician", "mus"),
            MimeType("application", "vnd.muvee.style", "msty"),
            MimeType("application", "vnd.neurolanguage.nlu", "nlu"),
            MimeType("application", "vnd.noblenet-directory", "nnd"),
            MimeType("application", "vnd.noblenet-sealer", "nns"),
            MimeType("application", "vnd.noblenet-web", "nnw"),
            MimeType("application", "vnd.nokia.n-gage.data", "ngdat"),
            MimeType("application", "vnd.nokia.n-gage.symbian.install", "n-gage"),
            MimeType("application", "vnd.nokia.radio-preset", "rpst"),
            MimeType("application", "vnd.nokia.radio-presets", "rpss"),
            MimeType("application", "vnd.novadigm.edm", "edm"),
            MimeType("application", "vnd.novadigm.edx", "edx"),
            MimeType("application", "vnd.novadigm.ext", "ext"),
            MimeType("application", "vnd.oasis.opendocument.chart", "odc"),
            MimeType("application", "vnd.oasis.opendocument.chart-template", "otc"),
            MimeType("application", "vnd.oasis.opendocument.database", "odb"),
            MimeType("application", "vnd.oasis.opendocument.formula", "odf"),
            MimeType("application", "vnd.oasis.opendocument.formula-template", "odft"),
            MimeType("application", "vnd.oasis.opendocument.graphics", "odg"),
            MimeType("application", "vnd.oasis.opendocument.graphics-template", "otg"),
            MimeType("application", "vnd.oasis.opendocument.image", "odi"),
            MimeType("application", "vnd.oasis.opendocument.image-template", "oti"),
            MimeType("application", "vnd.oasis.opendocument.presentation", "odp"),
            MimeType("application", "vnd.oasis.opendocument.presentation-template", "otp"),
            MimeType("application", "vnd.oasis.opendocument.spreadsheet", "ods"),
            MimeType("application", "vnd.oasis.opendocument.spreadsheet-template", "ots"),
            MimeType("application", "vnd.oasis.opendocument.text", "odt"),
            MimeType("application", "vnd.oasis.opendocument.text-master", "otm"),
            MimeType("application", "vnd.oasis.opendocument.text-template", "ott"),
            MimeType("application", "vnd.oasis.opendocument.text-web", "oth"),
            MimeType("application", "vnd.olpc-sugar", "xo"),
            MimeType("application", "vnd.oma.dd2+xml", "dd2"),
            MimeType("application", "vnd.openofficeorg.extension", "oxt"),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.presentationml.presentation",
                "pptx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.presentationml.slide",
                "sldx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.presentationml.slideshow",
                "ppsx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.presentationml.template",
                "potx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "xlsx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.spreadsheetml.template",
                "xltx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.wordprocessingml.document",
                "docx",
            ),
            MimeType(
                "application",
                "vnd.openxmlformats-officedocument.wordprocessingml.template",
                "dotx",
            ),
            MimeType("application", "vnd.osgi.dp", "dp"),
            MimeType("application", "vnd.palm", "oprc", "pdb", "pqa"),
            MimeType("application", "vnd.pg.format", "str"),
            MimeType("application", "vnd.pg.osasli", "ei6"),
            MimeType("application", "vnd.picsel", "efif"),
            MimeType("application", "vnd.pocketlearn", "plf"),
            MimeType("application", "vnd.powerbuilder6", "pbd"),
            MimeType("application", "vnd.previewsystems.box", "box"),
            MimeType("application", "vnd.proteus.magazine", "mgz"),
            MimeType("application", "vnd.publishare-delta-tree", "qps"),
            MimeType("application", "vnd.pvi.ptid1", "ptid"),
            MimeType(
                "application",
                "vnd.quark.quarkxpress",
                "qwd",
                "qwt",
                "qxb",
                "qxd",
                "qxl",
                "qxt",
            ),
            MimeType("application", "vnd.rar", "rar"),
            MimeType("application", "vnd.recordare.musicxml", "mxl"),
            MimeType("application", "vnd.recordare.musicxml+xml", "musicxml"),
            MimeType("application", "vnd.rim.cod", "cod"),
            MimeType("application", "vnd.rn-realmedia", "rm"),
            MimeType("application", "vnd.route66.link66+xml", "link66"),
            MimeType("application", "vnd.seemail", "see"),
            MimeType("application", "vnd.sema", "sema"),
            MimeType("application", "vnd.semd", "semd"),
            MimeType("application", "vnd.semf", "semf"),
            MimeType("application", "vnd.shana.informed.formdata", "ifm"),
            MimeType("application", "vnd.shana.informed.formtemplate", "itp"),
            MimeType("application", "vnd.shana.informed.interchange", "iif"),
            MimeType("application", "vnd.shana.informed.package", "ipk"),
            MimeType("application", "vnd.simtech-mindmapper", "twd", "twds"),
            MimeType("application", "vnd.smaf", "mmf"),
            MimeType("application", "vnd.smart.teacher", "teacher"),
            MimeType("application", "vnd.solent.sdkm+xml", "sdkd", "sdkm"),
            MimeType("application", "vnd.spotfire.dxp", "dxp"),
            MimeType("application", "vnd.spotfire.sfs", "sfs"),
            MimeType(
                "application",
                "vnd.sqlite3",
                "db",
                ".sqlite",
                "sqlite3",
                "db-wal",
                "sqlite-wal",
                "db-shm",
                "sqlite-shm",
            ),
            MimeType("application", "vnd.stardivision.calc", "sdc"),
            MimeType("application", "vnd.stardivision.draw", "sda"),
            MimeType("application", "vnd.stardivision.impress", "sdd"),
            MimeType("application", "vnd.stardivision.math", "smf"),
            MimeType("application", "vnd.stardivision.writer", "sdw", "vor"),
            MimeType("application", "vnd.stardivision.writer-global", "sgl"),
            MimeType("application", "vnd.sun.xml.calc", "sxc"),
            MimeType("application", "vnd.sun.xml.calc.template", "stc"),
            MimeType("application", "vnd.sun.xml.draw", "sxd"),
            MimeType("application", "vnd.sun.xml.draw.template", "std"),
            MimeType("application", "vnd.sun.xml.impress", "sxi"),
            MimeType("application", "vnd.sun.xml.impress.template", "sti"),
            MimeType("application", "vnd.sun.xml.math", "sxm"),
            MimeType("application", "vnd.sun.xml.writer", "sxw"),
            MimeType("application", "vnd.sun.xml.writer.global", "sxg"),
            MimeType("application", "vnd.sun.xml.writer.template", "stw"),
            MimeType("application", "vnd.sus-calendar", "sus", "susp"),
            MimeType("application", "vnd.svd", "svd"),
            MimeType("application", "vnd.symbian.install", "sis", "sisx"),
            MimeType("application", "vnd.syncml+xml", "xsm"),
            MimeType("application", "vnd.syncml.dm+wbxml", "bdm"),
            MimeType("application", "vnd.syncml.dm+xml", "xdm"),
            MimeType("application", "vnd.tao.intent-module-archive", "tao"),
            MimeType("application", "vnd.tmobile-livetv", "tmo"),
            MimeType("application", "vnd.trid.tpt", "tpt"),
            MimeType("application", "vnd.triscape.mxs", "mxs"),
            MimeType("application", "vnd.trueapp", "tra"),
            MimeType("application", "vnd.ufdl", "ufd", "ufdl"),
            MimeType("application", "vnd.uiq.theme", "utz"),
            MimeType("application", "vnd.umajin", "umj"),
            MimeType("application", "vnd.unity", "unityweb"),
            MimeType("application", "vnd.uoml+xml", "uoml"),
            MimeType("application", "vnd.vcx", "vcx"),
            MimeType(
                "application",
                "vnd.visio",
                "vsd",
                "vss",
                "vst",
                "vsw",
                "vsdx",
                "vssx",
                "vstx",
                "vssm",
                "vstm",
            ),
            MimeType("application", "vnd.visionary", "vis"),
            MimeType("application", "vnd.vsf", "vsf"),
            MimeType("application", "vnd.wap.sic", "sic"),
            MimeType("application", "vnd.wap.slc", "slc"),
            MimeType("application", "vnd.wap.wbxml", "wbxml"),
            MimeType("application", "vnd.wap.wmlc", "wmlc"),
            MimeType("application", "vnd.wap.wmlscriptc", "wmlsc"),
            MimeType("application", "vnd.webturbo", "wtb"),
            MimeType("application", "vnd.wordperfect", "wpd"),
            MimeType("application", "vnd.wqd", "wqd"),
            MimeType("application", "vnd.wt.stf", "stf"),
            MimeType("application", "vnd.xara", "xar"),
            MimeType("application", "vnd.xfdl", "xfdl"),
            MimeType("application", "vnd.yamaha.hv-dic", "hvd"),
            MimeType("application", "vnd.yamaha.hv-script", "hvs"),
            MimeType("application", "vnd.yamaha.hv-voice", "hvp"),
            MimeType("application", "vnd.yamaha.openscoreformat", "osf"),
            MimeType("application", "vnd.yamaha.openscoreformat.osfpvg+xml", "osfpvg"),
            MimeType("application", "vnd.yamaha.smaf-audio", "saf"),
            MimeType("application", "vnd.yamaha.smaf-phrase", "spf"),
            MimeType("application", "vnd.yellowriver-custom-menu", "cmp"),
            MimeType("application", "vnd.zul", "zir", "zirz"),
            MimeType("application", "vnd.zzazz.deck+xml", "zaz"),
            MimeType("application", "voicexml+xml", "vxml"),
            MimeType("application", "wasm", "wasm"),
            MimeType("application", "winhlp", "hlp"),
            MimeType("application", "wsdl+xml", "wsdl"),
            MimeType("application", "wspolicy+xml", "wspolicy"),
            MimeType("application", "x-7z-compressed", "7z"),
            MimeType("application", "x-abiword", "abw"),
            MimeType("application", "x-ace-compressed", "ace"),
            MimeType("application", "x-authorware-bin", "aab", "u32", "vox", "x32"),
            MimeType("application", "x-authorware-map", "aam"),
            MimeType("application", "x-authorware-seg", "aas"),
            MimeType("application", "x-bcpio", "bcpio"),
            MimeType("application", "x-bittorrent", "torrent"),
            MimeType("application", "x-bzip", "bz"),
            MimeType("application", "x-bzip2", "boz", "bz2"),
            MimeType("application", "x-cdlink", "vcd"),
            MimeType("application", "x-chat", "chat"),
            MimeType("application", "x-chess-pgn", "pgn"),
            MimeType("application", "x-cpio", "cpio"),
            MimeType("application", "x-csh", "csh"),
            MimeType("application", "x-debian-package", "deb", "udeb"),
            MimeType(
                "application",
                "x-director",
                "cct",
                "cst",
                "cxt",
                "dcr",
                "dir",
                "dxr",
                "fgd",
                "swa",
                "w3d",
            ),
            MimeType("application", "x-doom", "wad"),
            MimeType("application", "x-dtbncx+xml", "ncx"),
            MimeType("application", "x-dtbook+xml", "dtb"),
            MimeType("application", "x-dtbresource+xml", "res"),
            MimeType("application", "x-dvi", "dvi"),
            MimeType("application", "x-font-bdf", "bdf"),
            MimeType("application", "x-font-ghostscript", "gsf"),
            MimeType("application", "x-font-linux-psf", "psf"),
            MimeType("application", "x-font-otf", "otf"),
            MimeType("application", "x-font-pcf", "pcf"),
            MimeType("application", "x-font-snf", "snf"),
            MimeType("application", "x-font-ttf", "ttc", "ttf"),
            MimeType("application", "x-font-type1", "afm", "pfa", "pfb", "pfm"),
            MimeType("application", "x-futuresplash", "spl"),
            MimeType("application", "x-gnumeric", "gnumeric"),
            MimeType("application", "x-gtar", "gtar"),
            MimeType("application", "x-gzip", "gz", ".tgz"),
            MimeType("application", "x-hdf", "hdf"),
            MimeType("application", "x-iso9660-image", "iso", "isoimg", "cdr"),
            MimeType("application", "x-java-jnlp-file", "jnlp"),
            MimeType("application", "x-killustrator", "kil"),
            MimeType("application", "x-krita", "kra", "krz"),
            MimeType("application", "x-latex", "latex"),
            MimeType("application", "x-mobipocket-ebook", "mobi", "prc"),
            MimeType("application", "x-ms-application", "application"),
            MimeType("application", "x-ms-wmd", "wmd"),
            MimeType("application", "x-ms-wmz", "wmz"),
            MimeType("application", "x-ms-xbap", "xbap"),
            MimeType("application", "x-msaccess", "mdb"),
            MimeType("application", "x-msbinder", "obd"),
            MimeType("application", "x-mscardfile", "crd"),
            MimeType("application", "x-msclip", "clp"),
            MimeType("application", "x-msdownload", "bat", "com", "dll", "exe", "msi"),
            MimeType("application", "x-msmediaview", "m13", "m14", "mvb"),
            MimeType("application", "x-msmetafile", "wmf"),
            MimeType("application", "x-msmoney", "mny"),
            MimeType("application", "x-mspublisher", "pub"),
            MimeType("application", "x-msschedule", "scd"),
            MimeType("application", "x-msterminal", "trm"),
            MimeType("application", "x-mswrite", "wri"),
            MimeType("application", "x-netcdf", "cdf", "nc"),
            MimeType("application", "x-perl", "pm", ".pl"),
            MimeType("application", "x-pkcs12", "p12", "pfx"),
            MimeType("application", "x-pkcs7-certificates", "p7b", "spc"),
            MimeType("application", "x-pkcs7-certreqresp", "p7r"),
            MimeType("application", "x-python-code", "pyc", "pyo"),
            MimeType("application", "x-rar-compressed", "rar"),
            MimeType("application", "x-redhat-package-manager", "rpa"),
            MimeType("application", "x-rpm", "rpm"),
            MimeType("application", "x-sh", "sh"),
            MimeType("application", "x-shar", "shar"),
            MimeType("application", "x-shellscript", "sh"),
            MimeType("application", "x-shockwave-flash", "swf"),
            MimeType("application", "x-silverlight-app", "xap"),
            MimeType(
                "application",
                "x-sqlite3",
                "db",
                ".sqlite",
                "sqlite3",
                "db-wal",
                "sqlite-wal",
                "db-shm",
                "sqlite-shm",
            ),
            MimeType("application", "x-stuffit", "sit"),
            MimeType("application", "x-stuffitx", "sitx"),
            MimeType("application", "x-sv4cpio", "sv4cpio"),
            MimeType("application", "x-sv4crc", "sv4crc"),
            MimeType("application", "x-tar", "tar"),
            MimeType("application", "x-tcl", "tcl"),
            MimeType("application", "x-tex", "tex"),
            MimeType("application", "x-tex-tfm", "tfm"),
            MimeType("application", "x-texinfo", "texi", "texinfo"),
            MimeType("application", "x-trash", ""),
            MimeType("application", "x-ustar", "ustar"),
            MimeType("application", "x-wais-source", "src"),
            MimeType("application", "x-x509-ca-cert", "crt", "der"),
            MimeType("application", "x-xfig", "fig"),
            MimeType("application", "x-xpinstall", "xpi"),
            MimeType("application", "x-zip-compressed", "zip"),
            MimeType("application", "xenc+xml", "xenc"),
            MimeType("application", "xhtml+xml", "xht", "xhtml"),
            MimeType("application", "xml", "xml", "xpdl", "xsl"),
            MimeType("application", "xml-dtd", "dtd"),
            MimeType("application", "xop+xml", "xop"),
            MimeType("application", "xslt+xml", "xslt"),
            MimeType("application", "xspf+xml", "xspf"),
            MimeType("application", "xv+xml", "mxml", "xhvml", "xvm", "xvml"),
            MimeType("application", "yaml", "yaml", "yml"),
            MimeType("application", "zip", "zip"),
            MimeType("application", "zip-compressed", "zip"),
            MimeType("audio", "3gpp2", "3g2"),
            MimeType("audio", "aac", "aac", "m4a"),
            MimeType("audio", "aacp", "aacp"),
            MimeType("audio", "adpcm", "adp"),
            MimeType("audio", "aiff", "aiff", "aif", "aff"),
            MimeType("audio", "basic", "au", ".snd"),
            MimeType("audio", "flac", "flac"),
            MimeType("audio", "midi", "kar", "mid", "midi", "rmi"),
            MimeType(
                "audio",
                "mp4",
                "mp4",
                "m4a",
                "m4b",
                "m4p",
                "m4r",
                "m4v",
                "mp4v",
                "3gp",
                "3g2",
                "3ga",
                "3gpa",
                "3gpp",
                "3gpp2",
                "3gp2",
            ),
            MimeType("audio", "mp4a-latm", ""),
            MimeType("audio", "mpeg", "m2a", "m3a", "mp2", "mp2a", "mp3", "mpga"),
            MimeType("audio", "ogg", "oga", "ogg", "spx"),
            MimeType("audio", "opus", "opus"),
            MimeType("audio", "vnd.digital-winds", "eol"),
            MimeType("audio", "vnd.dts", "dts"),
            MimeType("audio", "vnd.dts.hd", "dtshd"),
            MimeType("audio", "vnd.lucent.voice", "lvp"),
            MimeType("audio", "vnd.ms-playready.media.pya", "pya"),
            MimeType("audio", "vnd.nuera.ecelp4800", "ecelp4800"),
            MimeType("audio", "vnd.nuera.ecelp7470", "ecelp7470"),
            MimeType("audio", "vnd.nuera.ecelp9600", "ecelp9600"),
            MimeType("audio", "vnd.wav", "wav"),
            MimeType("audio", "webm", "weba"),
            MimeType("audio", "x-matroska", "mka"),
            MimeType("audio", "x-mpegurl", "m3u"),
            MimeType("audio", "x-ms-wax", "wax"),
            MimeType("audio", "x-ms-wma", "wma"),
            MimeType("audio", "x-pn-realaudio", "ra", ".ram"),
            MimeType("audio", "x-pn-realaudio-plugin", "rmp"),
            MimeType("chemical", "x-cdx", "cdx"),
            MimeType("chemical", "x-cif", "cif"),
            MimeType("chemical", "x-cmdf", "cmdf"),
            MimeType("chemical", "x-cml", "cml"),
            MimeType("chemical", "x-csml", "csml"),
            MimeType("chemical", "x-xyz", "xyz"),
            MimeType("font", "otf", "otf"),
            MimeType("font", "woff", "woff"),
            MimeType("font", "woff2", "woff2"),
            MimeType("gcode", "", "gcode"),
            MimeType("image", "avif", "avif", "avifs"),
            MimeType("image", "bmp", "bmp"),
            MimeType("image", "cgm", "cgm"),
            MimeType("image", "g3fax", "g3"),
            MimeType("image", "gif", "gif"),
            MimeType("image", "heic", "heif", "heic"),
            MimeType("image", "ief", "ief"),
            MimeType("image", "jpeg", "jpe", "jpeg", "jpg", "pjpg", "jfif", "jfif-tbnl", "jif"),
            MimeType(
                "image",
                "pjpeg",
                "jpe",
                "jpeg",
                "jpg",
                "pjpg",
                "jfi",
                "jfif",
                "jfif-tbnl",
                "jif",
            ),
            MimeType("image", "png", "png"),
            MimeType("image", "prs.btif", "btif"),
            MimeType("image", "svg+xml", "svg", "svgz"),
            MimeType("image", "tiff", "tif", "tiff"),
            MimeType("image", "vnd.adobe.photoshop", "psd"),
            MimeType("image", "vnd.djvu", "djv", "djvu"),
            MimeType("image", "vnd.dwg", "dwg"),
            MimeType("image", "vnd.dxf", "dxf"),
            MimeType("image", "vnd.fastbidsheet", "fbs"),
            MimeType("image", "vnd.fpx", "fpx"),
            MimeType("image", "vnd.fst", "fst"),
            MimeType("image", "vnd.fujixerox.edmics-mmr", "mmr"),
            MimeType("image", "vnd.fujixerox.edmics-rlc", "rlc"),
            MimeType("image", "vnd.ms-modi", "mdi"),
            MimeType("image", "vnd.net-fpx", "npx"),
            MimeType("image", "vnd.wap.wbmp", "wbmp"),
            MimeType("image", "vnd.xiff", "xif"),
            MimeType("image", "webp", "webp"),
            MimeType("image", "x-adobe-dng", "dng"),
            MimeType("image", "x-canon-cr2", "cr2"),
            MimeType("image", "x-canon-crw", "crw"),
            MimeType("image", "x-cmu-raster", "ras"),
            MimeType("image", "x-cmx", "cmx"),
            MimeType("image", "x-epson-erf", "erf"),
            MimeType("image", "x-freehand", "fh", ".fh4", "fh5", "fh7", "fhc"),
            MimeType("image", "x-fuji-raf", "raf"),
            MimeType("image", "x-icns", "icns"),
            MimeType("image", "x-icon", "ico"),
            MimeType("image", "x-kodak-dcr", "dcr"),
            MimeType("image", "x-kodak-k25", "k25"),
            MimeType("image", "x-kodak-kdc", "kdc"),
            MimeType("image", "x-minolta-mrw", "mrw"),
            MimeType("image", "x-nikon-nef", "nef"),
            MimeType("image", "x-olympus-orf", "orf"),
            MimeType("image", "x-panasonic-raw", "raw", "rw2", "rwl"),
            MimeType("image", "x-pcx", "pcx"),
            MimeType("image", "x-pentax-pef", "pef", "ptx"),
            MimeType("image", "x-pict", "pct", "pic"),
            MimeType("image", "x-portable-anymap", "pnm"),
            MimeType("image", "x-portable-bitmap", "pbm"),
            MimeType("image", "x-portable-graymap", "pgm"),
            MimeType("image", "x-portable-pixmap", "ppm"),
            MimeType("image", "x-rgb", "rgb"),
            MimeType("image", "x-sigma-x3f", "x3f"),
            MimeType("image", "x-sony-arw", "arw"),
            MimeType("image", "x-sony-sr2", "sr2"),
            MimeType("image", "x-sony-srf", "srf"),
            MimeType("image", "x-xbitmap", "xbm"),
            MimeType("image", "x-xpixmap", "xpm"),
            MimeType("image", "x-xwindowdump", "xwd"),
            MimeType("message", "rfc822", "eml", "mht", "mhtml", "mime", "nws"),
            MimeType("model", "iges", "iges", "igs"),
            MimeType("model", "mesh", "mesh", "msh", "silo"),
            MimeType("model", "vnd.dwf", "dwf"),
            MimeType("model", "vnd.gdl", "gdl"),
            MimeType("model", "vnd.gtw", "gtw"),
            MimeType("model", "vnd.mts", "mts"),
            MimeType("model", "vnd.vtu", "vtu"),
            MimeType("model", "vrml", "vrml", "wrl"),
            MimeType("test", "mimetype", "test"),
            MimeType("text", "calendar", "ics", "ifb"),
            MimeType("text", "css", "css"),
            MimeType("text", "csv", "csv"),
            MimeType("text", "html", "htm", "html"),
            MimeType("text", "javascript", "js"),
            MimeType("text", "markdown", "md", ".markdown", "mdown", "markdn"),
            MimeType("text", "mathml", "mathml", "mml"),
            MimeType(
                "text",
                "plain",
                "conf",
                "def",
                "diff",
                "in",
                ".ksh",
                "list",
                "log",
                "pl",
                ".text",
                "txt",
            ),
            MimeType("text", "prs.lines.tag", "dsc"),
            MimeType("text", "richtext", "rtx"),
            MimeType("text", "sgml", "sgm", "sgml"),
            MimeType("text", "tab-separated-values", "tsv"),
            MimeType("text", "troff", "man", "me", ".ms", "roff", "t", ".tr"),
            MimeType("text", "uri-list", "uri", "uris", "urls"),
            MimeType("text", "vnd.curl", "curl"),
            MimeType("text", "vnd.curl.dcurl", "dcurl"),
            MimeType("text", "vnd.curl.mcurl", "mcurl"),
            MimeType("text", "vnd.curl.scurl", "scurl"),
            MimeType("text", "vnd.fly", "fly"),
            MimeType("text", "vnd.fmi.flexstor", "flx"),
            MimeType("text", "vnd.graphviz", "gv"),
            MimeType("text", "vnd.in3d.3dml", "3dml"),
            MimeType("text", "vnd.in3d.spot", "spot"),
            MimeType("text", "vnd.sun.j2me.app-descriptor", "jad"),
            MimeType("text", "vnd.wap.si", "si"),
            MimeType("text", "vnd.wap.sl", "sl"),
            MimeType("text", "vnd.wap.wml", "wml"),
            MimeType("text", "vnd.wap.wmlscript", "wmls"),
            MimeType("text", "x-asm", "asm", "s"),
            MimeType("text", "x-c", "c", ".cc", "cpp", "cxx", "dic", "h", ".hh"),
            MimeType("text", "x-fortran", "f", ".f77", "f90", "for"),
            MimeType("text", "x-java-source", "java"),
            MimeType("text", "x-markdown", "md", ".markdown", "mdown", "markdn"),
            MimeType("text", "x-pascal", "p", ".pas", "pp", ".inc"),
            MimeType("text", "x-python", "py"),
            MimeType("text", "x-setext", "etx"),
            MimeType("text", "x-uuencode", "uu"),
            MimeType("text", "x-vcalendar", "vcs"),
            MimeType("text", "x-vcard", "vcf"),
            MimeType("video", "3gpp", "3gp"),
            MimeType("video", "3gpp2", "3g2"),
            MimeType("video", "h261", "h261"),
            MimeType("video", "h263", "h263"),
            MimeType("video", "h264", "h264"),
            MimeType("video", "jpeg", "jpgv"),
            MimeType("video", "jpm", "jpgm", "jpm"),
            MimeType("video", "mj2", "mj2", "mjp2"),
            MimeType("video", "mp2t", "ts"),
            MimeType("video", "mp4", "mp4", "mp4v", "mpg4"),
            MimeType("video", "mpeg", "m1v", "m2v", "mpa", "mpe", "mpeg", "mpg"),
            MimeType("video", "ogg", "ogv"),
            MimeType("video", "quicktime", "mov", "qt"),
            MimeType("video", "vnd.fvt", "fvt"),
            MimeType("video", "vnd.mpegurl", "m4u", "mxu"),
            MimeType("video", "vnd.ms-playready.media.pyv", "pyv"),
            MimeType("video", "vnd.vivo", "viv"),
            MimeType("video", "webm", "webm"),
            MimeType("video", "x-f4v", "f4v"),
            MimeType("video", "x-fli", "fli"),
            MimeType("video", "x-flv", "flv"),
            MimeType("video", "x-m4v", "m4v"),
            MimeType("video", "x-matroska", "mkv"),
            MimeType("video", "x-ms-asf", "asf", "asx"),
            MimeType("video", "x-ms-wm", "wm"),
            MimeType("video", "x-ms-wmv", "wmv"),
            MimeType("video", "x-ms-wmx", "wmx"),
            MimeType("video", "x-ms-wvx", "wvx"),
            MimeType("video", "x-msvideo", "avi"),
            MimeType("video", "x-sgi-movie", "movie"),
            MimeType("x-conference", "x-cooltalk", "ice"),
        )
}
